apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-frontend
  namespace: DEPLOY_NAMESPACE
  labels:
    app: grafana-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        app: grafana-frontend
    spec:
      containers:
        - name: grafana
          image: NEW_ECR_IMAGE  # 🔹 Updated by GitHub Actions
          ports:
            - containerPort: 3000
          
          env:
            # Server Configuration
            - name: GF_SERVER_PROTOCOL
              value: "http"
            - name: GF_SERVER_DOMAIN
              value: "monitoring.dev.cloudbuilders.io"
            - name: GF_SERVER_ENFORCE_DOMAIN
              value: "true"
            - name: GF_SERVER_ROOT_URL
              value: "https://monitoring.dev.cloudbuilders.io/"
            - name: GF_SERVER_HTTP_PORT
              value: "3000"

            # Database Configuration (GitHub Secrets Replace These at Runtime)
            - name: GF_DATABASE_TYPE
              value: "postgres"
            - name: GF_DATABASE_HOST
              value: "GF_DATABASE_HOST_VALUE"  # Placeholder replaced by GitHub Actions
            - name: GF_DATABASE_NAME
              value: "GF_DATABASE_NAME_VALUE"
            - name: GF_DATABASE_USER
              value: "GF_DATABASE_USER_VALUE"
            - name: GF_DATABASE_PASSWORD
              value: "GF_DATABASE_PASSWORD_VALUE"
            - name: GF_DATABASE_SSL_MODE
              value: "verify-full"
            - name: GF_DATABASE_CA_CERT_PATH
              value: "/etc/ssl/certs/rds-ca.pem"

            # Plugin & TLS Configurations
            - name: GF_PLUGIN_TLS_SKIP_VERIFY
              value: "true"
            - name: GF_HTTP_TLS_SKIP_VERIFY
              value: "true"

            # OAuth Authentication Configuration
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: "OAuth"
            - name: GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              value: "tt4HINqCRHbQMxVnAAYimGbuzH96c5lH"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              value: "7Thx_llsPFTYdGqtZ5ytRKXEYmorZEsURHVOkprAuBN89_cmOrrrtCI3I6Hht4ch"
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: "openid email profile"
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: "https://dev-xwbc65ppnfy0ixvh.us.auth0.com/oauth2/authorize"
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: "https://dev-xwbc65ppnfy0ixvh.us.auth0.com/oauth2/token"
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: "https://dev-xwbc65ppnfy0ixvh.us.auth0.com/oauth2/userinfo"
            - name: GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME
              value: "email"
            - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_USE_PKCE
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN
              value: "false"
            - name: GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC
              value: "false"
            - name: GF_AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ORG_ATTRIBUTE_PATH
              value: "grafana_org_id"
            - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
              value: "contains(role[*], 'Admin') && 'Admin' || 'Viewer'"
            - name: GF_LOG_LEVEL
              value: "debug"  # For troubleshooting

          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: rds-ca-cert
              mountPath: "/etc/ssl/certs/rds-ca.pem"
              subPath: rds-ca.pem
              readOnly: true

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"

      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: rds-ca-cert
          secret:
            secretName: rds-ca-cert
