apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-frontend
  namespace: DEPLOY_NAMESPACE
  labels:
    app: grafana-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana-frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        app: grafana-frontend
    spec:
      containers:
        - name: grafana
          image: NEW_ECR_IMAGE  # 🔹 Updated by GitHub Actions
          ports:
            - containerPort: 3000

          env:
            - name: GF_SERVER_PROTOCOL
              value: "http"
            - name: GF_SERVER_DOMAIN
              value: "monitoring.cloudbuilders.io"
            - name: GF_SERVER_ENFORCE_DOMAIN
              value: "true"
            - name: GF_SERVER_ROOT_URL
              value: "https://monitoring.cloudbuilders.io/"
            - name: GF_SERVER_HTTP_PORT
              value: "3000"

              #smtp configuration
            - name: GF_SMTP_ENABLED
              value: "true"
            - name: GF_SMTP_HOST
              value: "email-smtp.us-east-1.amazonaws.com:587"  # Replace with your SES SMTP endpoint (region)
            - name: GF_SMTP_USER
              value: "GF_SMTP_USER_PLACEHOLDER"   #added in github secrets
            - name: GF_SMTP_PASSWORD
              value: "GF_SMTP_PASSWORD_PLACEHOLDER"   #added in github secrets
            - name: GF_SMTP_FROM_ADDRESS
              value: "srinivasulun@mycloudbuilders.com"  # Replace with your SES verified email address
            - name: GF_SMTP_FROM_NAME
              value: "Grafana Alerts"
            - name: GF_SMTP_SKIP_VERIFY
              value: "true"
            - name: GF_SMTP_STARTTLS
              value: "true"
            - name: GF_SMTP_EHLO_IDENTITY
              value: "localhost"

            # Database Configuration
            - name: GF_DATABASE_TYPE
              value: "postgres"
            - name: GF_DATABASE_HOST
              value: "grafana-db.czo2u80k8ov3.us-east-1.rds.amazonaws.com:5432"
            - name: GF_DATABASE_NAME
              value: "grafana-postgres"
            - name: GF_DATABASE_USER
              value: "GF_DATABASE_USER_PLACEHOLDER"  #added in github secrets
            - name: GF_DATABASE_PASSWORD
              value: "GF_DATABASE_PASSWORD_PLACEHOLDER"  #added in github secrets
            - name: GF_DATABASE_SSL_MODE
              value: "verify-full" # SSL is disabled since no certificate is used
            - name: GF_DATABASE_CA_CERT_PATH
              value: "/etc/ssl/certs/rds-ca.pem"
            - name: GF_PLUGIN_TLS_SKIP_VERIFY
              value: "true"
            - name: GF_HTTP_TLS_SKIP_VERIFY
              value: "true"
            
            - name: GF_USERS_ALLOW_ORG_CREATE
              value: "true"  # Enable organization creation via API
            
            - name: GF_INSTALL_PLUGINS
              value: "grafana-clickhouse-datasource, grafana-athena-datasource"


            # Plugin & TLS Configurations
            - name: GF_ALERTING_TLS_SKIP_VERIFY
              value: "true"
            - name: GF_ALERTING_CONTACT_POINT_SLACK_TLS_SKIP_VERIFY
              value: "true"
            - name: GF_TLS_SKIP_VERIFY_INSECURE
              value: "true"
            
        
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: rds-ca-cert
              mountPath: "/etc/ssl/certs/rds-ca.pem"
              subPath: rds-ca.pem
              readOnly: true

      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: rds-ca-cert
          secret:
            secretName: rds-ca-cert
